server:
  port: 8081
spring:
  application:
    name: payment-processing-service
  kafka:
    bootstrap-servers: localhost:9092,localhost:9095
    properties:
      schema.registry.url: http://localhost:8088
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        auto.register.schemas: true
    consumer:
      group-id: payment-processing-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
